layout_spectrum: 1
typography_spectrum: 0.7744681
color:
  lightness: 0
  brandStrength: 1
  saturation: 0.4914894
  rhythmicContrast: 0.8241871
  brandColors:
    - '#CA5441'
    - '#000000'
    - '#F1F1F2'
    - '#DEA399'
    - '#E7CAC6'
name: Sassarico
